name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Create PDF
      uses: mkrakowitzer/actions-makepdfs@1.1
      with:
        # Location of markdown files in github repository
        markdown_dir: $GITHUB_WORKSPACE
        # Location to output PDF files to
        # output_dir: $GITHUB_WORKSPACE/tmp


